# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badges.BadgeLevel'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
