# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20160309_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
