# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
