# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveSmallIntegerField()),
                ('minor', models.PositiveSmallIntegerField()),
                ('patch', models.PositiveSmallIntegerField()),
                ('show', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('scheduled', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ('-major', '-minor', '-patch'),
            },
        ),
        migrations.CreateModel(
            name='ReleaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('B', 'bugfix'), ('F', 'feature'), ('O', 'other')], max_length=5)),
                ('description', models.CharField(max_length=500)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='releases.Release')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('major', 'minor', 'patch')]),
        ),
    ]
