# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
