# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appaccount',
            options={'verbose_name_plural': 'app accounts'},
        ),
    ]
