# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:41
from __future__ import unicode_literals

from django.db import migrations

def cutoff_protocol(apps, schema_editor):
    Models = ['GenericEvent', 'SubmittedEvent', 'ReadEvent',
              'RatedEvent', 'ScoredEvent', 'ClickedEvent']
    for Model in Models:
        for event in apps.get_model('events', Model).objects.all():
            event.obj = event.obj.replace('https:','').replace('http:','')
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_submittedevent'),
    ]

    operations = [
        migrations.RunPython(cutoff_protocol),
    ]
