# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('badges.badge',),
        ),
        migrations.CreateModel(
            name='CodeSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.skill',),
        ),
        migrations.CreateModel(
            name='ForSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.codeskill',),
        ),
        migrations.CreateModel(
            name='IfElseSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.codeskill',),
        ),
        migrations.CreateModel(
            name='IfSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.codeskill',),
        ),
        migrations.CreateModel(
            name='SequenceSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.codeskill',),
        ),
        migrations.CreateModel(
            name='WhileSkill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('skills.codeskill',),
        ),
    ]
