# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160407_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='browser_location',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
