# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_browser_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AddField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
