# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160413_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='browser_location',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
