# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0004_app_login_config_json'),
        ('kb', '0002_auto_20151223_1840'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningUnitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Activity')),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.LearningUnit')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observables', to='collections.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Activity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.GenericEvent')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Observable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='observable',
            name='completed_by',
            field=models.ManyToManyField(related_name='observations', through='collections.Observation', to='kb.UserProfile'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='activities',
            field=models.ManyToManyField(through='collections.LearningUnitItem', to='collections.Activity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='learning_units',
            field=models.ManyToManyField(to='collections.LearningUnit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_tasks', through='collections.ActivityCompletion', to='kb.UserProfile'),
        ),
    ]
