# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunititem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
