# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_auto_20160215_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
