# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningunit',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
