# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_auto_20160407_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
