# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:17
from __future__ import unicode_literals

from django.db import migrations
from django.http import QueryDict
from re import sub

def convert_submitted_to_completions(apps, schema_editor):
    SubmittedEvent = apps.get_model('events', 'SubmittedEvent')
    ActivityCompletion = apps.get_model('collections', 'ActivityCompletion')
    Activity = apps.get_model('collections', 'Activity')
    for event in SubmittedEvent.objects.all():
        if 'code.org' not in event.obj:
            continue

        submission = QueryDict(event.submission)
        if 'pass' not in submission or 'testResult' not in submission:
            continue

        if submission['testResult'] == "100" or submission['pass'] == "false":
            continue

        try:
            activity = Activity.objects.get(
                url__endswith=sub(r"https?", "", event.obj));
        except Activity.DoesNotExist:
            print('Cannot find activity %s' % (event.obj,))

        if ActivityCompletion.objects.filter(user=event.user.profile,
                activity=activity).exists():
            continue

        ActivityCompletion.objects.create(user=event.user.profile,
                datetime=event.timestamp,
                activity=activity, score=int(submission['testResult']))


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_activitycompletion_score'),
        ('events', '0003_auto_20160418_1641'),
    ]

    operations = [
        migrations.RunPython(convert_submitted_to_completions),
    ]
