# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_login_config_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='adaptor_class',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
