# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20160217_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='adaptor_class',
            new_name='connector_class',
        ),
    ]
