# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_auto_20160201_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercredentials',
            name='params',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
