# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20160215_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='brincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
