# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_institute_brincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='brincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
