# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20160302_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
