# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldump',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 21, 14, 46, 18, 785002, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
