# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.4 on 2016-03-21 14:46
=======
# Generated by Django 1.9.4 on 2016-04-04 10:26
>>>>>>> master
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldump',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 4, 10, 26, 26, 147797, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
